# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [2]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.8


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [3]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

import numpy as np

array1 = np.arange(1000000)
array2 = list(range(1000000))

In [4]:
%time
display(array1*2)

CPU times: user 13 µs, sys: 2 µs, total: 15 µs
Wall time: 26.7 µs


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [5]:
%time
array_temp = [(element * 2) for element in array2]
display(array_temp)

CPU times: user 12 µs, sys: 1 µs, total: 13 µs
Wall time: 25.7 µs


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

### Exercício 2

In [6]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
array3 = np.arange(10)
array3[5:8] = 0
array3

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [29]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
array4 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ]
)

array4[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [41]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
array5 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6], 
        [7, 8, 9]
    ]
)
print(array5[2])
print()
print(array5[:2, 1:])


[7 8 9]

[[2 3]
 [5 6]]


### Exercício 5

In [43]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [59]:
arr1 = np.arange(15).reshape(15,1)
arr1
arr1.transpose()

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

### Exercício 6

In [60]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [63]:
result = [(arrayx if conditional else array) for arrayx, array, conditional in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [74]:
array_temp2 = zip(xarr, yarr, cond)
for item in array_temp2:
    print(item)
print(array_temp2)
for (x, y, c) in zip(xarr, yarr, cond):
    if c:
        print(x)
    else:
        print(y)

(1.1, 2.1, True)
(1.2, 2.2, False)
(1.3, 2.3, True)
(1.4, 2.4, True)
(1.5, 2.5, False)
1.1
2.2
1.3
1.4
2.5


### Exercício 7

In [75]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
a = np.arange(10)
print(a)
np.save('array_a', a)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
# Depois carregue o array do disco no array B
b = np.load('array_a.npy')
print(b)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [3]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [79]:
print(obj.unique())

['c' 'a' 'd' 'b']


### Exercício 9

In [1]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [4]:
data = resp.json()
# display(data)
issues = pd.DataFrame(data, columns = ['number', 'title', 'labels', 'state'])
display(issues)

number                                              title  \
0    44845  BUG: `groupby(...).agg()` with numpy transform...   
1    44844  CI: Flaky ResourceWarning('unclosed file <_io....   
2    44842  ENH: inverse / reverse function of convert_dtypes   
3    44841  PERF: Faster SparseArray.__getitem__ for boole...   
4    44839  REGR: allow reindexing datetimelike with upcas...   
5    44837  BUG: read_excel surprisingly filling empty lev...   
6    44833  ENH: Add a parameter in rolling() to control t...   
7    44832                      PERF: array_equivalent_object   
8    44830                  BUG: IntervalArray.__cmp__(pd.NA)   
9    44829                    BUG: SparseArray.min/max skipna   
10   44825  BUG: rolling with method='table' and then appl...   
11   44824  BUG: Fix regression in groupby.rolling.corr/co...   
12   44823  API: Breaking Changes in 2.0 (without deprecat...   
13   44822                                CI: Troubleshoot CI   
14   44821  BUG: Inconsistent behaviour in DataFrameGroupB...   
15   44820  REF: use dispatch_reduction_ufunc in PandasArr...   
16   44819  API: hide NumericIndex from public top-level n...   
17   44818  BUG: Inconsistent conversion of missing column...   
18   44817         CI: Install more packages from conda-forge   
19   44813  BUG: Unexpected side effects within `agg` func...   
20   44809                                  CI: PyPy3 testing   
21   44803  BUG: `groupby.apply()` inconsistently indexes ...   
22   44802                      TYP tighten `any` return type   
23   44801       TYP: mostly missing return annotations in IO   
24   44799  BUG: _repr_*_ methods should not iterate over ...   
25   44798  PERF: avoid going through .values for reindexi...   
26   44796                        PERF: DataFrame.__setitem__   
27   44794  ENH: Initial implementation of support for SQL...   
28   44793     ENH: support np.add.reduce, np.multiply.reduce   
29   44792  BUG: MultiIndex constructed with nulls inconsi...   

                                               labels state  
0   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
1   [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
2   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
3                                                  []  open  
4                                                  []  open  
5   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
6   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
7                                                  []  open  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
9   [{'id': 49182326, 'node_id': 'MDU6TGFiZWw0OTE4...  open  
10  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
11  [{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgx...  open  
12  [{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...  open  
13  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15                                                 []  open  
16  [{'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
19  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
20  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22  [{'id': 717120670, 'node_id': 'MDU6TGFiZWw3MTc...  open  
23  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
26  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
27                                                 []  open  
28                                                 []  open  
29  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros,
# consulte a tabela e retorne os dados em dataframe do Pandas

In [5]:
import sqlite3

connection = sqlite3.connect('issues.db')
print('Opening database')

Opening database


In [9]:
cursor = connection.cursor()

In [10]:
# Command DDL

sql_create_table = '''
CREATE TABLE IF NOT EXISTS issues (
    number INTEGER PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    labels TEXT,
    state TEXT NOT NULL
);
'''

In [11]:
# Executing instruction

cursor.execute(sql_create_table)

In [15]:
# Iserting function
sql_insert = 'INSERT INTO issues VALUES (?, ?, ?, ?, ?);'

In [16]:
# List with some records
record_set = [
    (0, 0, 'Breves respostas para grandes questões', 'Stephen Hawking', 'Not read'),
    (1, 1, 'O livro dos cinco anéis', 'Musashi', 'Reading'),
]

In [17]:
#For each element of my list, save in database using the insert sql function
for record in record_set:
    cursor.execute(sql_insert, record)

In [18]:
# Sending data to database
connection.commit()

In [19]:
# Setting sql function to consult all records
sql_get_all = 'SELECT * FROM issues;'

In [20]:
# Using the cursor to run all database and save the data in data variable
cursor.execute(sql_get_all)
data = cursor.fetchall()

In [26]:
# For each record of the data, print the record
for item in data:
    print('Livro ID: (%d, %d), título: %s de autor: %s e status: %s.' % item)

Livro ID: (0, 0), título: Breves respostas para grandes questões de autor: Stephen Hawking e status: Not read.
Livro ID: (1, 1), título: O livro dos cinco anéis de autor: Musashi e status: Reading.
[(0, 0, 'Breves respostas para grandes questões', 'Stephen Hawking', 'Not read'), (1, 1, 'O livro dos cinco anéis', 'Musashi', 'Reading')]


In [24]:
# Saving data into data frame of Pandas package
issues_df = pd.DataFrame(data, columns=['id', 'number', 'title', 'label', 'state'])

display(issues_df)

id  number                                   title            label  \
0   0       0  Breves respostas para grandes questões  Stephen Hawking   
1   1       1                 O livro dos cinco anéis          Musashi   

      state  
0  Not read  
1   Reading

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
